version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: approved-postgres
    ports:
      - "5431:5432"
    environment:
      POSTGRES_DB: approved
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
