"""Update users.

Revision ID: 23b96b94639e
Revises:
Create Date: 2024-07-13 21:15:50.225366

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "23b96b94639e"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
