"""Update users.

Revision ID: f0d23d815cac
Revises: 23b96b94639e
Create Date: 2024-07-13 21:57:43.788794

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "f0d23d815cac"
down_revision: Union[str, None] = "23b96b94639e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
