environment: ${ENVIRONMENT}

# Database configuration.
database:
  dialect: ${DB_DIALECT}
  host: ${DB_HOST}
  port: ${DB_PORT}
  db_name: ${DB_NAME}
  username: ${DB_USER}
  password: ${DB_PASSWORD}
  # Application specific database configuration.
  common:
    # app: Refers to data used by web application.
    app: common_app
  reviewer:
    # app: Refers to data used by web application.
    app: reviewer_app

# Authentication configuration.
secret_key: ${SECRET_KEY}
secret_algorithm: HS256

# Github authentication
github_token: ${GITHUB_TOKEN}

request_timeout: 600.0
max_concurrent_file_reviews: 5

# LLM configuration.
provider_to_llm:
  openai: gpt-4o
llm_provider: openai
llm_config:
